# Generated by Django 6.0.4 on 2026-04-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='faces_detected',
            field=models.JSONField(default=dict),
        ),
    ]
